### ISSUE TITLE
The speed controls doesn't show up on all the videos.. only some 

### ISSUE THREAD

**Issue by awwad98** [CODESIGN2/media-playback-speed#9]
**Describe the bug**

Only some of the videos that I put up on my website show the speed controls .. the majority of the videos don't show any speed controls

**The Context**

* WordPress Version: 5.9
* Other plugins: nothing that's worth mentioning
* Theme: Hello Elementor
* URL:  https://www.drghadabadran.com

**Expected behavior**

**Screenshots**

**Files**

<details>
<summary>If you are running a service where you cannot provide a public url, without login details; please `click-to-expand` instructions for sending snapshots of complete web pages.</summary>

Please attach a zip file containing a `Webpage, Complete` saved page. See the attached screenshot from Google Chrome

![image](https://user-images.githubusercontent.com/2605791/131392883-8816c39c-93d4-4bdf-a1f2-2d73837ae6a5.png)

Webpage, Complete automatically gets all the CSS, JS, Iamges; and you can then zip the folder and attach.
 
> Care should be taken to ensure nothing protected, sensitive, bigoted or harmful is included in the upload.
 
</details>

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lewiscowles1986** [comment]
Sorry if this offends, but is this spam? 😂

The screenshot looks like it's from an older folder on my computer, and there are no video's or audio on the linked page...

**Comment by awwad98** [comment]
No it's not spam .. and I didn't include a screenshot .. the issue is
simple .. it's a website for my client
I could make an account for you so you can check out the courses and videos
inside the website and see why the speed buttons aren't showing up on some
videos

**Comment by Lewiscowles1986** [comment]
Hi 👋,

I'm sorry if you are having a bad day, or if there has been some confusion, but you are coming across really poorly.
Please take a minute to reconsider and adjust before responding. 

1. Fill in the template, or I'll close and lock the issue.
   > Other plugins: nothing that's worth mentioning
   
   Humor me. It's in the template for issues for a reason. This is a tested free and open-source plugin. If you cannot be bothered to help me out by filling in a form. Why would I try to help solve your problem?

2. Make a public page that shows the problem, without other plugin interactions, or you do the work to find which plugin is causing the issue yourself; by disabling plugins, changing to a free theme without a page builder; so we have something to discuss where I am not being asked to do your job.

## Why?

All I have here is a wordpress version and theme, that implies a non-free plugin. 

The link given in `URL` requires me to do more work than it is reasonable to ask me to do.

There is no expected behavior or details about the specifics of your setup:

* Do you use the WordPress shortcode this was originally designed for?
* Do you use the new Video block, which is documented to need you to implement UI
 
There is a screenshot that was left in the template, rather than deleted. Nothing about the device this was encountered on.

You have to help people to help you, if you want their help.

**Comment by Lewiscowles1986** [comment]
Here is an example of the site working on WordPress 5.9 for the avoidance of doubt:

* https://wp.dh.codesign2.co.uk/2018/02/test-skip/
* https://wp.dh.codesign2.co.uk/sample-video/
